package preparation

import (
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var errNoSource = errors.New("no supported source language found")

// Serena 1.7 project create infers languages interactively. Passing its documented
// --language options avoids stdin prompts without starting language servers.
func serenaLanguages(root string) ([]string, error) {
	extensions := map[string]string{
		".py": "python", ".pyi": "python", ".js": "typescript", ".jsx": "typescript", ".mjs": "typescript", ".cjs": "typescript", ".ts": "typescript", ".tsx": "typescript",
		".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin", ".kts": "kotlin", ".rb": "ruby", ".dart": "dart", ".cs": "csharp", ".php": "php",
		".c": "cpp", ".h": "cpp", ".cc": "cpp", ".cpp": "cpp", ".hpp": "cpp", ".swift": "swift", ".sh": "bash", ".lua": "lua", ".luau": "luau",
		".ex": "elixir", ".exs": "elixir", ".erl": "erlang", ".scala": "scala", ".clj": "clojure", ".cljs": "clojure", ".hs": "haskell", ".ml": "ocaml", ".nix": "nix", ".tf": "terraform", ".zig": "zig", ".vue": "vue", ".svelte": "svelte",
	}
	skip := map[string]bool{".git": true, ".agent-team": true, ".serena": true, ".beads": true, "graphify-out": true, "node_modules": true, ".venv": true, "venv": true, "vendor": true, "dist": true, "build": true, "target": true}
	set := map[string]bool{}
	count := 0
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		count++
		if count > 50000 {
			return errors.New("Serena language selection exceeds file limit; configure project languages explicitly")
		}
		if entry.IsDir() {
			if path != root && skip[entry.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Type().IsRegular() {
			if language := extensions[strings.ToLower(filepath.Ext(entry.Name()))]; language != "" {
				set[language] = true
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(set) == 0 {
		return nil, errNoSource
	}
	languages := make([]string, 0, len(set))
	for language := range set {
		languages = append(languages, language)
	}
	sort.Strings(languages)
	return languages, nil
}

type serenaPartial struct{ Root, TreeDigest string }

func serenaPartialPath(root string) string {
	return filepath.Join(root, ".agent-team", "dependencies", "prepared", "serena-partial.json")
}

// Record exact output from a failed attempt that began with no project config.
// A later retry can isolate only these unchanged generated bytes.
func recordSerenaPartial(root string) error {
	hash, err := graphTreeDigest(filepath.Join(root, ".serena"))
	if err != nil {
		return err
	}
	path := serenaPartialPath(root)
	if err := ensureDirectory(root, filepath.Dir(path)); err != nil {
		return err
	}
	data, _ := json.Marshal(serenaPartial{Root: root, TreeDigest: hash})
	return writeReceipt(path, data)
}

func recoverSerenaPartial(root string) (func(), bool, error) {
	path := serenaPartialPath(root)
	data, err := readProjectFile(root, path, 4096)
	if err != nil {
		return nil, false, nil
	}
	var receipt serenaPartial
	if json.Unmarshal(data, &receipt) != nil || receipt.Root != root || receipt.TreeDigest == "" {
		return nil, false, nil
	}
	dir := filepath.Join(root, ".serena")
	hash, err := graphTreeDigest(dir)
	if err != nil || hash != receipt.TreeDigest {
		return nil, false, nil
	}
	if err := ensureDirectory(root, filepath.Dir(path)); err != nil {
		return nil, false, err
	}
	backup, err := os.MkdirTemp(filepath.Dir(path), ".serena-partial-")
	if err != nil {
		return nil, false, err
	}
	if err := os.Remove(backup); err != nil {
		return nil, false, err
	}
	if err := os.Rename(dir, backup); err != nil {
		return nil, false, err
	}
	return func() { _ = os.RemoveAll(backup) }, true, nil
}
